In [1]:
# Importing dependencies

from learntools.core import binder
import numpy as np
import string # import string for q3

binder.bind(globals())

from learntools_ex import *

print("Setup Complete")

Setup Complete


## **Questions**

### **IMPORTANT**: You **don't** have to delete any `q{n}.check()` or `q{n}.hint()` or `q{n}_sol = question_{n}()`. Please make sure that the function name and function signature match the question and the example given. Additionally, all functions should be runnable or your solution will not be evaluated.

## **Q1:** Create a one-dimensional NumPy array of the numbers from 5 to 905, counting by 10, exclusive 905?

In [6]:
def question_1():
    return np.arange(5, 905, 10)


q1_sol = question_1()
q1.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q2**: Create the same NumPy array using a Python range and a list? (Hint: create a list)

In [2]:
def question_2():
    return np.array(list(range(5, 905, 10)))

q2_sol = question_2()
q2.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q3**: How might you create a NumPy array of the capital letters, A-Z? (Hint: Ever heard of string.ascii_uppercase?)

In [8]:
def question_3():
    return np.array(list(string.ascii_uppercase))

q3_sol = question_3()
q3.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q4**: Create a ten-element NumPy array object of all zeros and a six-element NumPy array object of all ones.

In [4]:
def question_4() -> tuple:
    sol_1 = np.zeros(10)
    sol_2 = np.ones(6)
    return(sol_1, sol_2)

q4_sol_1, q4_sol_2 = question_4()
q4.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q5**: Given an 2-D array, print the third column.

In [5]:
input = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])


def question_5(input):
    third_column = input [:, 2]
    print(third_column)
    return(third_column)


q5_sol = question_5(input)
q5.check()

[33 66 99]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q6**: Create an array of the shape (3, 4), filled with 64-bit integer zeros.

In [7]:
def question_6():
    array = np.zeros((3, 4), dtype = np.int64)
    print(array)
    return array


q6_sol = question_6()
q6.check()

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q7**: Split an array into 3 equal-sized sub-arrays.

In [8]:
input = np.arange(7, 34, 1).reshape(9, 3)



def question_7(input):
    sub_array_1 = input[:3, :] 
    sub_array_2 = input[3:6, :]
    sub_array_3 = input[6:, :] 
    return [sub_array_1, sub_array_2, sub_array_3]


q7_sol_1, q7_sol_2, q7_sol_3 = question_7(input)
q7.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q8**: Return the last 2 elements by each of the first two rows of the (3,4) array. 

In [3]:
input = np.arange(1, 13, 1).reshape(3, 4)


def question_8(input):
    result = input[:2, -2:]
    return result


q8_sol = question_8(input)
q8.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q9**: Return how many elements are greater than 5 in an array.

In [4]:
input = np.arange(1, 13, 1).reshape(3, 4)


def question_9(input):
    greater_than_5 = np.sum(input > 5)
    return greater_than_5


q9_sol = question_9(input)
q9.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q10**: Delete the second column from an array and insert the following new column in the same place.

In [10]:
input = np.array([[34, 72, 33], [82, 22, 32], [59, 84, 10]])
insert_data = np.array([[37, 37, 37]])


def question_10(input, insert_data):
    delete_sec = np.delete(input, 1, axis = 1)
    result = np.insert(delete_sec, 1, insert_data, axis = 1)
    return result


q10_sol = question_10(input, insert_data)
q10.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q11**: Compute the Euclidean distance between each pair of consecutive points in a given 2D NumPy array and append the result as a new column. Pad with 0 for missing data.

Euclidian distance between two points $(x_1, y_1)$ and $(x_2, y_2)$ is $\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$.  

In [9]:
input = np.array([[1, 2], [4, 6], [7, 8], [10, 10]])


def question_11(input):
    distance = np.diff(input, axis=0)  # Compute differences
    euclidean_distance = np.sqrt(np.sum(distance**2, axis=1))
    euclidean_distance = np.append(euclidean_distance, 0)
    result = np.column_stack((input, euclidean_distance))
    return result
q11.hint()
q11_sol = question_11(input)
q11.check()

<IPython.core.display.Javascript object>

<span style="color:#3366cc">Hint:</span> Compute differences with np.diff(), then calculate Euclidean distances and append 0.

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q12**: Remove consecutive duplicates from a NumPy array.

In [11]:
input = np.array([[1, 1], [2, 1], [3, 3], [3, 3], [2, 1], [1, 1]])


def question_12(input):
    duplicates = np.vstack([input[0], input[1:] [np.any(input[1:] != input[:-1], axis = 1)]])
    return duplicates


q12_sol = question_12(input)
q12.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q13**: Given a 2D NumPy array representing strokes, normalize all rows by subtracting the mean of each column and dividing by the standard deviation, but avoid division by zero.
$X_{\text{normalized}} = \frac{X - \mu}{\sigma}$

In [16]:
input = np.array([[10, 20, 30], [15, 24, 33], [8, 18, 29], [14, 22, 32]])


def question_13(input):
    mean = np.mean(input, axis=0)
    std_dev = np.std(input, axis=0, ddof=0)
    
    std_dev = np.where(std_dev == 0, 1, std_dev)
    
    return (input - mean) / std_dev

q13.hint()
q13_sol = question_13(input)
q13.check()

<IPython.core.display.Javascript object>

<span style="color:#3366cc">Hint:</span> Subtract the column means and divide by the standard deviations (ensure no division by zero).

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q14**: Delete the second column from an array and insert a new column at the same position where each value is the sum of its corresponding row.

In [17]:
input = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


def question_14(input):
    delete_sec = np.delete(input, 1, axis = 1)
    sum_row = np.sum(input, axis = 1)
    result = np.insert(delete_sec, 1, sum_row, axis = 1)
    return result

q14_sol = question_14(input)
q14.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q15**: Extract Unique Characters from a NumPy Array of Strings
Given a 1D NumPy array of strings, extract all unique characters present in the array and sort by their ASCII values.

In [ ]:
from collections import Counter

input = np.array(["hello", "world", "numpy", "rocks"])

def question_15(input):
    full_string = "".join(input)
    
    unique_chars = set(full_string)
    
    return unique_chars

q15_sol = question_15(input)
q15.check()
q15.hint()

print("Output:", q15_sol)

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

<IPython.core.display.Javascript object>

<span style="color:#3366cc">Hint:</span> Concatenate the strings, build a set of unique characters, and sort them.

Output: {'p', 'c', 'o', 'k', 'n', 'h', 'u', 'w', 'd', 'm', 'r', 's', 'e', 'l', 'y'}


## **Q16**: Generate a dictionary that maps each unique character to a unique index starting with 0, sorted by ascending ASCII value.

In [2]:
input = np.array(["a", "b", "c", "d", "a", "c", "e"])


def question_16(input):
    unique_chars = sorted(set(input))
    dictionary_char = {char: idx for idx, char in enumerate(unique_chars)}
    return dictionary_char

q16_sol = question_16(input)
q16.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q17**: Convert a List of 2D traces into a Single NumPy Array
Given a list of 2D traces (each being a NumPy array of shape `(N, 2)`), stack them into a single NumPy array.

In [3]:
input = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8], [9, 10]])]


def question_17(input):
    single_array = np.vstack(input)
    return single_array

q17_sol = question_17(input)
q17.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q18**: Convert a List of Text Labels into a NumPy Array of Integer Encodings
Given a vocabulary dictionary and a string of space-separated labels, convert the text into a NumPy array of indices.

In [ ]:
input = {
    "hello": 0,
    "numpy": 1,
    "rocks": 2,
    "world": 3,
    "python": 4,
    "data": 5,
    "science": 6,
}

labels = "hello rocks"

def question_18(input, labels):
    split = labels.split()
    encoding_array = [input[word] for word in split]
    return np.array(encoding_array)

q18_sol = question_18(input, labels)
q18.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q19**: Extract Non-Zero Differences from an Array
Given a NumPy array of first-order differences, extract only non-zero differences using masking.

In [ ]:
input = np.array([[3, 4], [0, 0], [-2, 1]])


def question_19(input):
    differences = np.diff(input, axis = 1)
    row_mask = np.any(differences != 0, axis = 1)
    return input[row_mask] #used input instead of differences here is to pick the row from the original input array that had at least one non-zero difference

q19_sol = question_19(input)
q19.check()
q19.hint()
print(q19_sol)

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

<IPython.core.display.Javascript object>

<span style="color:#3366cc">Hint:</span> Create a mask to filter out rows that are all zeros and use it to index the array.

[[ 3  4]
 [-2  1]]


## **Q20**: Time Series Data Transformation and Feature Engineering

### *Problem Statement:*  
You are given a time series dataset representing sensor readings from multiple devices. Each row consists of sensor values at a specific timestamp. Your task is to preprocess and extract meaningful features from the dataset by performing the following transformations:

### *Steps to Follow:*
1. Normalize Each Sensor Reading  
- Subtract the mean and divide by the standard deviation for each column.  
- Avoid division by zero by replacing std=0 with 1.  
2. Detect and Mask Anomalous Values
- If a sensor reading is more than 2.5 standard deviations away from the mean, replace it with NaN.
3. Interpolate Missing Values (NaN Handling)
- Fill NaN values with the average of the nearest non-NaN neighbors.
4. Extract First-Order Differences
- Compute the difference between consecutive time steps for each sensor.
- Padding with 0 for missing data
5. Add Binary Columns for Missing Data
- Stack All Features into a Final Matrix
Create new columns `missing_flag` that is `1` where original data was `NaN`, otherwise `0`.
6. Stack All Features into a Final Matrix
- The final dataset should have normalized values, first-order differences, and the missing flag.

Expected shape (5, 9)

In [5]:
input_data = np.array([
    [1.0, 10.0, 100.0],
    [2.0, 20.0, 200.0],
    [3.0, 30.0, 10000.0],  # Outlier
    [4.0, 40.0, 400.0],
    [5.0, 50.0, 500.0],
])

def question_20(input_array):
    #1
    mean = np.mean(input_array, axis=0)
    std = np.std(input_array, axis=0)
    std[std == 0] = 1 # making sure no division by 0 occur here
    normalized = (input_array - mean) / std

    print("Normalized:\n", normalized)

    #2
    mask = np.abs(normalized) > 2.5
    masked = np.where(mask, np.nan, normalized)

    print("Masked (NaN for anomalies):\n", masked)

    #3
    for i in range(masked.shape[1]):
        col = masked[:, i]
        nan_indices = np.isnan(col)
        if np.any(nan_indices):  # If NaNs exist, interpolate
            valid_indices = np.where(~nan_indices)[0]
            if valid_indices.size > 0:
                col[nan_indices] = np.interp(np.where(nan_indices)[0], valid_indices, col[valid_indices])

    interpolated = masked
    print("Interpolated:\n", interpolated)

    #4
    diffs = np.diff(interpolated, axis=0, prepend=0)  # Compute difference with padding for missing data

    print("First Order Differences:\n", diffs)

    #5
    missing_flags = np.isnan(masked).astype(int)

    print("Missing Flags:\n", missing_flags)

    #6 
    final = np.hstack([normalized, diffs, missing_flags]) #stack for final matrix

    print("Final Stacked Output:\n", final)
    return final


q20_sol = question_20(input_data)
q20.check()
q20.hint()


Normalized:
 [[-1.41421356 -1.41421356 -0.55118039]
 [-0.70710678 -0.70710678 -0.52542429]
 [ 0.          0.          1.99867281]
 [ 0.70710678  0.70710678 -0.47391211]
 [ 1.41421356  1.41421356 -0.44815602]]
Masked (NaN for anomalies):
 [[-1.41421356 -1.41421356 -0.55118039]
 [-0.70710678 -0.70710678 -0.52542429]
 [ 0.          0.          1.99867281]
 [ 0.70710678  0.70710678 -0.47391211]
 [ 1.41421356  1.41421356 -0.44815602]]
Interpolated:
 [[-1.41421356 -1.41421356 -0.55118039]
 [-0.70710678 -0.70710678 -0.52542429]
 [ 0.          0.          1.99867281]
 [ 0.70710678  0.70710678 -0.47391211]
 [ 1.41421356  1.41421356 -0.44815602]]
First Order Differences:
 [[-1.41421356 -1.41421356 -0.55118039]
 [ 0.70710678  0.70710678  0.02575609]
 [ 0.70710678  0.70710678  2.5240971 ]
 [ 0.70710678  0.70710678 -2.47258492]
 [ 0.70710678  0.70710678  0.02575609]]
Missing Flags:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Final Stacked Output:
 [[-1.41421356 -1.41421356 -0.55118039 -1.4142135

<IPython.core.display.Javascript object>

<span style="color:#cc3333">Incorrect:</span> Incorrect value for `q20_sol`: `array([[-1.41421356, -1.41421356, -0.55118039, -1.41421356, -1.41421356,
        -0.55118039,  0.        ,  0.        ,  0.        ],
       [-0.70710678, -0.70710678, -0.52542429,  0.70710678,  0.70710678,
         0.02575609,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.99867281,  0.70710678,  0.70710678,
         2.5240971 ,  0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678, -0.47391211,  0.70710678,  0.70710678,
        -2.47258492,  0.        ,  0.        ,  0.        ],
       [ 1.41421356,  1.41421356, -0.44815602,  0.70710678,  0.70710678,
         0.02575609,  0.        ,  0.        ,  0.        ]])`

<IPython.core.display.Javascript object>

<span style="color:#3366cc">Hint:</span> Perform normalization, detect anomalies, interpolate missing values, compute first-order differences, and finally stack the features along with a missing data flag.